# Generated by Django 5.2.7 on 2025-10-28 09:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MassNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Тема уведомления (1-200 символов)",
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="Тема уведомления",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Текст сообщения для рассылки",
                        verbose_name="Текст сообщения",
                    ),
                ),
                (
                    "immediately",
                    models.BooleanField(
                        default=False,
                        help_text="Отправить рассылку немедленно",
                        verbose_name="Немедленная отправка",
                    ),
                ),
                (
                    "priority_order",
                    models.JSONField(
                        default=list,
                        help_text="Порядок каналов отправки в формате JSON массива",
                        verbose_name="Порядок приоритета каналов",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает отправки"),
                            ("processing", "В процессе отправки"),
                            ("completed", "Завершена"),
                            ("failed", "Завершена с ошибками"),
                            ("cancelled", "Отменена"),
                        ],
                        default="pending",
                        help_text="Текущий статус выполнения рассылки",
                        max_length=15,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "total_recipients",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Общее количество получателей рассылки",
                        verbose_name="Всего получателей",
                    ),
                ),
                (
                    "sent_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество успешно отправленных уведомлений",
                        verbose_name="Отправлено",
                    ),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество неудачных отправок",
                        verbose_name="Ошибок отправки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата и время запланированной отправки",
                        null=True,
                        verbose_name="Запланирована на",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время начала отправки"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время завершения"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Пользователь, создавший рассылку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Массовая рассылка",
                "verbose_name_plural": "Массовые рассылки",
                "db_table": "mass_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает отправки"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка отправки"),
                            ("no_channels", "Нет доступных каналов"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Статус доставки",
                    ),
                ),
                (
                    "delivered_via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("sms", "SMS"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Канал доставки",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Описание ошибки при неудачной отправке",
                        verbose_name="Сообщение об ошибке",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время отправки"
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="notification.massnotification",
                        verbose_name="Рассылка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_recipients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылок",
                "db_table": "notification_recipients",
            },
        ),
        migrations.AddField(
            model_name="massnotification",
            name="users",
            field=models.ManyToManyField(
                help_text="Пользователи, которым предназначена рассылка",
                related_name="mass_notifications",
                through="notification.NotificationRecipient",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователи для рассылки",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["delivery_status", "sent_at"],
                name="notificatio_deliver_327fc4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["user", "sent_at"], name="notificatio_user_id_f955d5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationrecipient",
            unique_together={("notification", "user")},
        ),
        migrations.AddIndex(
            model_name="massnotification",
            index=models.Index(
                fields=["status", "scheduled_for"], name="mass_notifi_status_aaf9d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="massnotification",
            index=models.Index(
                fields=["created_at"], name="mass_notifi_created_eef270_idx"
            ),
        ),
    ]
